### ISSUE TITLE
Parse error: syntax error, unexpected 'return' (T_RETURN) 

### ISSUE THREAD

**Issue by nathanchicken** [marionnewlevant/craft-twig_perversion#1]
Unfortunately this is not working as is for me, but I could see where the problem lies.  It's very possible it's a PEBCAK thing but here goes:

I have a simple template like this:

```
{% macro getImageTransforms() %}
    {# Relies on MN Twig Perversion #}
    {% set sizes = 'Hello' %}

    {% return sizes %}
{% endmacro %}
```

Literally nothing else in the template at this point and I get a PHP error, something like:

> Parse error: syntax error, unexpected 'return' (T_RETURN) in [..]/craft/app/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code on line 40

Investigating it could be an environment issue.  I'm a bit of a noob with that, but it seems to be down to `Return_Node.php` and the `\n` linebreaks:

Line 403 of `craft/app/vendor/twig/twig/lib/Twig/Environment.php` has `eval('?>'.$content);` - I simply echoed that out just to see what the output was.  It'd actually print out a `\n` rather than an actual line break.  Relatively speaking I'm a noob with Twig and PHP and more of a front end guy, but simply changing the `\n` in `Return_Node.php` and replacing them with actual line breaks in my text editor fixed the problem for me and then the plugin works.

Lastly - thanks.  Macros returning variables is something I wanted in my first experience of Twig and Craft so I think we're going to find this plugin appearing in a lot of projects :)

**Comment by marionnewlevant** [comment]
Fixing (later today). I had `->write('ob_end_clean();\n')` where I should have had `->write("ob_end_clean();\n")`
