### ISSUE TITLE
[Feature Request] Power operator

### ISSUE THREAD

**Issue by benface** [marionnewlevant/craft-twig_perversion#13]
We **really** shouldn't be doing this in Twig, but on a project I've needed it... so I think it fits this plugin's purpose.

PHP has the `**` operator for exponentiation [since 5.6](http://php.net/manual/en/language.operators.arithmetic.php). Here's what it would look like in Twig:

```
{% set number = 2 %}
{% set squaredNumber = number ** 2 %}

{{ number }} == 4
```

Thank you! :)

**Comment by marionnewlevant** [comment]
@benface Twig has the power operator built in: [math](https://twig.symfony.com/doc/2.x/templates.html#math), so apparently it's not a perversion.

**Comment by benface** [comment]
Oh wow I had no idea haha. Gotta improve my Googling skills. Thank you!

**Comment by marionnewlevant** [comment]
It was the easiest of fixes!
