### ISSUE TITLE
[Feature Request] Append values to arrays

### ISSUE THREAD

**Issue by benface** [marionnewlevant/craft-twig_perversion#14]
Twig insists on making this a difficult/awkward task:

```
{% set array = [] %}
{% for item in items %}
    {% set array = array|merge([item]) %}
{% endfor %}
```

I would like to request a new `append` tag, making it easier:

```
{% set array = [] %}
{% for item in items %}
    {% append item to array %}
{% endfor %}
```

It could also be called `push` or `add`.

**Comment by marionnewlevant** [comment]
I am going to decline this. I think merge is enough.
https://github.com/marionnewlevant/craft-twig_perversion/issues/15#issuecomment-492506364
