### ISSUE TITLE
[Feature Request] Set the value of a hash's key

### ISSUE THREAD

**Issue by benface** [marionnewlevant/craft-twig_perversion#15]
Similar to #14 but for hashes.

Right now, if you want to change the value associated to a specific key in a hash, you have to use `merge`:

```
{% set hash = {
    'apples': 5,
    'bananas': 6,
} %}
{% set hash = hash|merge({ 'apples': 8 }) %}
```

I would like to request a new `assign` tag, making it a breeze:

```
{% set hash = {
    'apples': 5,
    'bananas': 6,
} %}
{% assign hash.apples = 8 %}
```

It could also work with arrays:

```
{% set array = ['apple', 'banana'] %}
{% assign array[0] = 'orange' %}
{# array is now ['orange', 'banana'] #}
```

**Comment by marionnewlevant** [comment]
I'm going to decline this.

One reason is that twig uses `hash.apples` in all of these cases:
- `hash` is an associative array with key `apples`
- `hash` is an object with property `apples`
- `hash` is an object with method `apples`
- `hash` is an object with method `getApples`
- `hash` is an object with method `isApples`

The other is that we already have `merge`, and I don't see this as doing anything `merge` doesn't.
