### ISSUE TITLE
[Feature Request] While loops

### ISSUE THREAD

**Issue by benface** [marionnewlevant/craft-twig_perversion#16]
e.g.
```
{% set i = 0 %}
{% while i < 5 %}
    {% set i = i + 1 %}
{% endwhile %}
```

**Comment by marionnewlevant** [comment]
Need to figure out how this would play with the `for` tag loop variables. Also, needs to work with `break` and `continue`

**Comment by marionnewlevant** [comment]
In process with this, waiting for this fix to land: [https://github.com/craftcms/cms/issues/4271](https://github.com/craftcms/cms/issues/4271)

**Comment by marionnewlevant** [comment]
Done! Works with the break tag (and continue), and also the loop variables.

**Comment by benface** [comment]
Nice! Good work :)
