### ISSUE TITLE
Strict comparision operators

### ISSUE THREAD

**Issue by piotrpog** [marionnewlevant/craft-twig_perversion#18]
Readme says that this plugin allows us to use strict comparison (===) - but isn't it available in Craft already without any plugins?
update:
it seems i was wrong - please close this issue :)

**Comment by marionnewlevant** [comment]
Twig has [sameas](https://twig.symfony.com/doc/2.x/tests/sameas.html) test, so with Twig Perversion you can do `{% if a === b %}` or `{% if a !== b %}`, but without, you can get the same with `{% if a is sameas b %}` or {% if a is not sameas b %}`.

And if I had known about the `sameas` operator, I probably wouldn't have added `===`, but I find the `===` easier to read, and it's there now, and not worth a breaking change to remove it. So here we are.
