### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CatAnonymous** [marionnewlevant/craft-twig_perversion#19]
Twig code
``
{% set loop = 1 %}
{% continue %}
``
PHP error: 'continue' not in the 'loop' or 'switch' context
This php code is executed even if it is not in the loop
``
if (array_key_exists('loop', $context)) {
                    ++$context['loop']['index0'];
                    ++$context['loop']['index'];
                    $context['loop']['first'] = false;
                    if (isset($context['loop']['length'])) {
                        --$context['loop']['revindex0'];
                        --$context['loop']['revindex'];
                        $context['loop']['last'] = 0 === $context['loop']['revindex0'];
                    }
                }
``

Twig code:
``
{% break %}
``
PHP error: 'break' not in the 'loop' or 'switch' context

**Comment by marionnewlevant** [comment]
`{% break %}` and `{% continue %}` only make sense when in a `{% for ... %}` loop

**Comment by CatAnonymous** [comment]
> `{% break %}`và `{% continue %}`chỉ có ý nghĩa khi trong một `{% for ... %}`vòng lặp



> `{% break %}`và `{% continue %}`chỉ có ý nghĩa khi trong một `{% for ... %}`vòng lặp

You can add a SyntaxError Twig for this
