### ISSUE TITLE
Add new `is numeric` test

### ISSUE THREAD

**Issue by lindseydiloreto** [marionnewlevant/craft-twig_perversion#2]
For whatever reason, fabpot doesn't think it's worth adding an `is numeric` test to Twig. I happen to strongly disagree.

https://github.com/twigphp/Twig/issues/1861

Would you mind adding a test like this to Twig Perversion?

```
{% if myVar is numeric %}
    {# Do something which requires a number #}
{% endif %}
```

**Comment by marionnewlevant** [comment]
added in 1.0.1

**Comment by lindseydiloreto** [comment]
Brilliant!! Thanks Marion! :)
