### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by peteeveleigh** [marionnewlevant/craft-twig_perversion#23]
Is there a current plan for making sure the plugin works in Craft 4?

I'm happy to attempt a PR if needed.

**Comment by marionnewlevant** [comment]
I am just now starting to look at this. I would love a pr!

**Comment by peteeveleigh** [comment]
Will see what I can do! Happy to help if I can.

**Comment by marionnewlevant** [comment]
I have gotten myself off the dime and am figuring out how to do the
craft 4 port. So it's coming!

**Comment by marionnewlevant** [comment]
Done!

**Comment by peteeveleigh** [comment]
Oh! Awesome! 
I've been working on updating some of our plugins for Craft 4 today and was thinking I'd take a look at doing a PR for yours this evening. I can put my feet up now, thank you!
