### ISSUE TITLE
JSON Decode

### ISSUE THREAD

**Issue by bossanova808** [marionnewlevant/craft-twig_perversion#3]
Twig is missing a matching json decode filter for it's json encode.

This can be handy in e.g. squirting json api results from javascript in to twig templates...I am thinking e.g. of Algolia search results...this would remove the need to use a separate template language like Hogan

It's trivially easy to add I think, but it seems like this would fit well with the 'pushing twig boundaries' behaviour of your twig plugin

```
    public function getFilters() {
        return array(
            'json_decode'   => new \Twig_Filter_Method($this, 'jsonDecode'),
        );
    }

    public function jsonDecode($str) {
        return json_decode($str);
    }
```

Mind you when you go down this path there's a million handy filters etc. you could add - but I do think this one is quite a useful and natural fit...

I can do a PR if you prefer...but the above is basically it :)

**Comment by marionnewlevant** [comment]
I agree, and will add it! Thanks.
