### ISSUE TITLE
Feature request: splice array

### ISSUE THREAD

**Issue by benface** [marionnewlevant/craft-twig_perversion#4]
You can add items to an array with `merge` and extract parts of an array with `slice`, but you can't remove items from an array in Twig. So it would be great to add a `splice` filter based on PHP's `array_splice()`. Thank you! :)

**Comment by marionnewlevant** [comment]
I will look into it!

**Comment by marionnewlevant** [comment]
Done!

**Comment by benface** [comment]
Awesome! Thank you :)
