### ISSUE TITLE
"Array to string conversion" when calling macro that returns an array in a child template

### ISSUE THREAD

**Issue by benface** [marionnewlevant/craft-twig_perversion#5]
This is a weird one. I have created this project to reproduce the issue: http://benface.com/files/twigperversion-bug.zip (includes DB dump but it's nothing more than a sample installation of Craft with the plugin installed... still, if you want to use it, the CP credentials are admin / password)

Look at the templates. If you load `/index` in your browser, you'll see that it crashes, while `/index2` doesn't. Both are child templates, extending `_layout.twig` which imports some macros. Twig macros are available to child templates, but for some reason if you use the `{% return %}` statement that this plugin provides to return an array or array-like object (in this example it's a collection of elements), that macro doesn't work outside the specific template that imports it. In the child of a base template that imports it, the macro is recognized, but it crashes with the error message: `Array to string conversion`. `/index2` works because it re-imports the macros file, but that shouldn't be required.

Let me know if you need more information. Thank you!

**Comment by marionnewlevant** [comment]
Since twig 2.0, macros imported in a file are not available in child templates. See [https://twig.symfony.com/doc/1.x/deprecated.html#macros](https://twig.symfony.com/doc/1.x/deprecated.html#macros). `index2` is correct - the macros need to be imported everywhere they are used.

It sort of almost works, but craft/app/vendor/twig/twig/lib/Twig/Template.php starting line 699 attempts to report the error, and then things fail. So lousy error reporting, but otherwise not a bug.

**Comment by benface** [comment]
@marionnewlevant Thank you for your answer. But Craft 2.x doesn't use Twig 2.0, does it? Or else how do you explain that it works when {% return %} isn't used?

**Comment by marionnewlevant** [comment]
@benface You are right, latest Craft seems to be using twig 1.24.1. So relying on the `import` from the `extends` is deprecated, but it should work.

What breaks things is returning an array, not just the return. So `{% return ['thing'] %}` causes it to fail, and `{% return 'thing' %}` does not.

Given that it is deprecated (and won't work at all in Craft 3, which does use the newer Twig), and that I can't figure out how to fix it anyway (and doubt there is any way to fix it cleanly), I'm going to leave things as they are (broken).

**Comment by benface** [comment]
@marionnewlevant Makes sense, thank you for investigating. :)
