### ISSUE TITLE
Add Combined Operators

### ISSUE THREAD

**Issue by lindseydiloreto** [marionnewlevant/craft-twig_perversion#8]
It would be really cool if you could append or add/subtract with a single operator...

    {% set exampleString ~= "lorem ipsum" %}

    {% set exampleNumber += 100 %}
    {% set exampleNumber -= 100 %}

http://php.net/manual/en/language.operators.assignment.php

**Comment by marionnewlevant** [comment]
Also ++ and --... I need to figure out how to get this to work.

**Comment by lindseydiloreto** [comment]
Oh, good idea! Those would be pretty helpful.

**Comment by marionnewlevant** [comment]
Requires mucking with the set tag. I think I'll pass

**Comment by lindseydiloreto** [comment]
Fair enough, thanks for looking into it!
